[package]
name = "pazzfraze"
version = "0.1.0"
authors = ["negamartin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8"
rand = "0.7"
rand_chacha = "0.2"
